### ISSUE TITLE
请问什么时候能开源谢谢

### ISSUE THREAD

**Issue by weishao-996** [datake/AdaGCN#2]
请问什么时候能开源谢谢

**Comment by zhangtanma** [comment]
同问

**Comment by JhuoW** [comment]
I tried to reproduce this paper [here](https://github.com/zhuo931077127/AdaGCN)~  However, there may be some bugs

**Comment by datake** [comment]
Sorry for the delay. I have updated the code. Please let me know if there is any code issue.
